import { ModelConfig } from "./types";

export const AVAILABLE_MODELS: ModelConfig[] = [
  // ─── Budget tier ───
  {
    id: "mistral-small",
    name: "Mistral Small 4",
    provider: "mistral",
    apiModel: "mistral-small-2603",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.3,
    contextWindow: 256000,
    bestFor: ["general", "coding"],
    tier: "budget",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "openai",
    apiModel: "gpt-4.1-nano",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1000000,
    bestFor: ["general", "coding"],
    tier: "budget",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3.2",
    provider: "deepseek",
    apiModel: "deepseek-chat",
    inputCostPer1M: 0.14,
    outputCostPer1M: 0.28,
    contextWindow: 128000,
    bestFor: ["general", "analysis", "writing", "coding"],
    tier: "budget",
  },
  {
    id: "grok-4-fast",
    name: "Grok 4.1 Fast",
    provider: "xai",
    apiModel: "grok-4.1-fast",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.5,
    contextWindow: 2000000,
    bestFor: ["large_document", "general"],
    tier: "budget",
  },
  {
    id: "codestral",
    name: "Codestral",
    provider: "mistral",
    apiModel: "codestral",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    contextWindow: 256000,
    bestFor: ["coding"],
    tier: "budget",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 mini",
    provider: "openai",
    apiModel: "gpt-4.1-mini",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.8,
    contextWindow: 1000000,
    bestFor: ["writing", "general", "coding"],
    tier: "budget",
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "google",
    apiModel: "gemini-3.1-flash-lite-preview",
    inputCostPer1M: 0.25,
    outputCostPer1M: 1.5,
    contextWindow: 1000000,
    bestFor: ["general", "coding", "writing"],
    tier: "budget",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    apiModel: "gemini-2.5-flash",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.5,
    contextWindow: 1000000,
    bestFor: ["general", "coding", "writing", "analysis", "math_reasoning", "image_multimodal"],
    tier: "budget",
  },
  {
    id: "devstral",
    name: "Devstral 2",
    provider: "mistral",
    apiModel: "devstral-2512",
    inputCostPer1M: 0.4,
    outputCostPer1M: 2.0,
    contextWindow: 262000,
    bestFor: ["coding"],
    tier: "budget",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    provider: "google",
    apiModel: "gemini-3-flash-preview",
    inputCostPer1M: 0.5,
    outputCostPer1M: 3.0,
    contextWindow: 1000000,
    bestFor: ["coding", "general", "writing", "analysis"],
    tier: "budget",
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "openai",
    apiModel: "o4-mini",
    inputCostPer1M: 0.55,
    outputCostPer1M: 2.2,
    contextWindow: 200000,
    bestFor: ["math_reasoning", "coding", "analysis"],
    tier: "budget",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "deepseek",
    apiModel: "deepseek-reasoner",
    inputCostPer1M: 0.55,
    outputCostPer1M: 2.19,
    contextWindow: 128000,
    bestFor: ["math_reasoning", "coding", "analysis"],
    tier: "budget",
  },

  // ─── Mid tier ───
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    provider: "openai",
    apiModel: "gpt-5.2",
    inputCostPer1M: 0.875,
    outputCostPer1M: 7.0,
    contextWindow: 400000,
    bestFor: ["coding", "writing", "general", "analysis"],
    tier: "mid",
  },
  {
    id: "claude-haiku",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    apiModel: "claude-haiku-4-5",
    inputCostPer1M: 1.0,
    outputCostPer1M: 5.0,
    contextWindow: 200000,
    bestFor: ["coding", "general", "writing"],
    tier: "mid",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    apiModel: "gemini-2.5-pro",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 1000000,
    bestFor: ["image_multimodal", "large_document", "analysis", "coding", "writing"],
    tier: "mid",
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "openai",
    apiModel: "gpt-5.3-codex",
    inputCostPer1M: 1.75,
    outputCostPer1M: 14.0,
    contextWindow: 400000,
    bestFor: ["coding", "analysis"],
    tier: "mid",
  },
  {
    id: "mistral-large",
    name: "Mistral Large 3",
    provider: "mistral",
    apiModel: "mistral-large-latest",
    inputCostPer1M: 2.0,
    outputCostPer1M: 6.0,
    contextWindow: 256000,
    bestFor: ["general", "writing", "analysis", "coding"],
    tier: "mid",
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    apiModel: "gpt-4.1",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 1000000,
    bestFor: ["writing", "coding", "general", "analysis"],
    tier: "mid",
  },

  // ─── Premium tier ───
  {
    id: "o3",
    name: "o3",
    provider: "openai",
    apiModel: "o3",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 200000,
    bestFor: ["math_reasoning", "coding", "analysis"],
    tier: "premium",
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    provider: "google",
    apiModel: "gemini-3.1-pro-preview",
    inputCostPer1M: 2.0,
    outputCostPer1M: 12.0,
    contextWindow: 1000000,
    bestFor: ["coding", "analysis", "large_document", "writing", "math_reasoning", "image_multimodal"],
    tier: "premium",
  },
  {
    id: "grok-4",
    name: "Grok 4",
    provider: "xai",
    apiModel: "grok-4-0709",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 256000,
    bestFor: ["analysis", "math_reasoning", "coding"],
    tier: "premium",
  },
  {
    id: "claude-sonnet",
    name: "Claude Sonnet 4.6",
    provider: "anthropic",
    apiModel: "claude-sonnet-4-6",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 1000000,
    bestFor: ["coding", "analysis", "writing", "math_reasoning"],
    tier: "premium",
  },
  {
    id: "claude-opus",
    name: "Claude Opus 4.6",
    provider: "anthropic",
    apiModel: "claude-opus-4-6",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 1000000,
    bestFor: ["coding", "analysis", "math_reasoning", "writing"],
    tier: "premium",
  },
];

export function getModelById(id: string): ModelConfig | undefined {
  return AVAILABLE_MODELS.find((m) => m.id === id);
}

export function getModelsForCategory(category: string): ModelConfig[] {
  return AVAILABLE_MODELS.filter((m) => m.bestFor.includes(category as never));
}

export function getModelsByProvider(provider: string): ModelConfig[] {
  return AVAILABLE_MODELS.filter((m) => m.provider === provider);
}
